[package]
name = "monitor_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xrandr = "0.1.1"
serde_json = "1.0"
clap = { version = "3.1.18", features = ["derive"] }
